"""rename player table to players

Revision ID: 541feca52bcf
Revises: cdc716c7e2ba
Create Date: 2022-05-11 10:40:54.218632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541feca52bcf'
down_revision = 'cdc716c7e2ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('player')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='player_pkey')
    )
    op.drop_table('players')
    # ### end Alembic commands ###
