"""adding pile_four and pile_five to games

Revision ID: 7ac7bcced493
Revises: 8a4a21f93ad4
Create Date: 2022-05-25 12:26:47.311959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ac7bcced493'
down_revision = '8a4a21f93ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('pile_four', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('games', sa.Column('pile_five', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'pile_five')
    op.drop_column('games', 'pile_four')
    # ### end Alembic commands ###
