"""making all players columns non-nullable

Revision ID: 7b29b6dd2748
Revises: 541feca52bcf
Create Date: 2022-05-16 10:30:11.289240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b29b6dd2748'
down_revision = '541feca52bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('players', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('players', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
