"""adding games and games_x_players tables

Revision ID: 8f16dc4b130d
Revises: 7b29b6dd2748
Create Date: 2022-05-16 12:41:36.108857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f16dc4b130d'
down_revision = '7b29b6dd2748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.Enum('WAITING_FOR_CHOICE', 'PLACING_DRAW', 'FINAL_ASSIGNMENT', 'COMPLETED', name='gamestatus'), nullable=False),
    sa.Column('active_player_index', sa.SmallInteger(), nullable=False),
    sa.Column('use_advanced_scoring', sa.Boolean(), nullable=False),
    sa.Column('assign_wilds_on_take', sa.Boolean(), nullable=False),
    sa.Column('deck', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_deck_index', sa.SmallInteger(), nullable=False),
    sa.Column('pile_one', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pile_two', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pile_three', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games_x_players',
    sa.Column('game_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_index', sa.SmallInteger(), nullable=False),
    sa.Column('starting_card', sa.Enum('WILD', 'PLUS_TWO', 'RAT', 'RABBIT', 'SNAKE', 'SHEEP', 'MONKEY', 'CHICKEN', 'DOG', name='cardtype'), nullable=False),
    sa.Column('took_this_round', sa.Boolean(), nullable=False),
    sa.Column('wild_count', sa.SmallInteger(), nullable=False),
    sa.Column('wild_assignments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plus_two_count', sa.SmallInteger(), nullable=False),
    sa.Column('rat_count', sa.SmallInteger(), nullable=False),
    sa.Column('rabbit_count', sa.SmallInteger(), nullable=False),
    sa.Column('snake_count', sa.SmallInteger(), nullable=False),
    sa.Column('sheep_count', sa.SmallInteger(), nullable=False),
    sa.Column('monkey_count', sa.SmallInteger(), nullable=False),
    sa.Column('chicken_count', sa.SmallInteger(), nullable=False),
    sa.Column('dog_count', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games_x_players')
    op.drop_table('games')
    # ### end Alembic commands ###
